// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxBEcpQxAsEGj9z9kQeeamhbVZdNZzvQ0',
    appId: '1:912094437032:web:29725ea9a1d38c8d43ac9d',
    messagingSenderId: '912094437032',
    projectId: 'first-app-fe804',
    authDomain: 'first-app-fe804.firebaseapp.com',
    storageBucket: 'first-app-fe804.appspot.com',
    measurementId: 'G-CYXGG413TC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAwHhi2JBH3Peqy-_3kEGNrh5x3WN1nR4',
    appId: '1:912094437032:android:f439b23d202ed34e43ac9d',
    messagingSenderId: '912094437032',
    projectId: 'first-app-fe804',
    storageBucket: 'first-app-fe804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHUq63iy5E6blOOrVy6L7x1oVfiuXYx0I',
    appId: '1:912094437032:ios:008f3f8bcfe21e7d43ac9d',
    messagingSenderId: '912094437032',
    projectId: 'first-app-fe804',
    storageBucket: 'first-app-fe804.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHUq63iy5E6blOOrVy6L7x1oVfiuXYx0I',
    appId: '1:912094437032:ios:9be92149b94707a143ac9d',
    messagingSenderId: '912094437032',
    projectId: 'first-app-fe804',
    storageBucket: 'first-app-fe804.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
