// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsA9sv11sWr0HA50_w9nCkjIfqh2i5ob8',
    appId: '1:443203921083:web:e9fe64930127ebbe22359e',
    messagingSenderId: '443203921083',
    projectId: 'first-app-70a90',
    authDomain: 'first-app-70a90.firebaseapp.com',
    storageBucket: 'first-app-70a90.appspot.com',
    measurementId: 'G-4X48C50TNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiSU5yLxYepI7LPguO2c_zqrKNU7q2yo',
    appId: '1:443203921083:android:cd4448ddc7e2a27422359e',
    messagingSenderId: '443203921083',
    projectId: 'first-app-70a90',
    storageBucket: 'first-app-70a90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiSq3C1Xu1ag6dIAwvoZ1WRtSSn3E8kqs',
    appId: '1:443203921083:ios:8504411a27341bc822359e',
    messagingSenderId: '443203921083',
    projectId: 'first-app-70a90',
    storageBucket: 'first-app-70a90.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiSq3C1Xu1ag6dIAwvoZ1WRtSSn3E8kqs',
    appId: '1:443203921083:ios:61d3b76c0e663cd222359e',
    messagingSenderId: '443203921083',
    projectId: 'first-app-70a90',
    storageBucket: 'first-app-70a90.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
